# protocol.py

# Client ↔ Leader
CLIENT_JOIN = "CLIENT_JOIN"
CHATROOMS_LIST = "CHATROOMS_LIST"
CREATE_CHATROOM = "CREATE_CHATROOM"
JOIN_CHATROOM = "JOIN_CHATROOM"
ROOM_ASSIGNMENT = "ROOM_ASSIGNMENT"

# Client ↔ Chatroom Server
CHAT_MSG = "CHAT_MSG"

# Server ↔ Server
HEARTBEAT = "HEARTBEAT"
ELECTION = "ELECTION"
LEADER_ANNOUNCE = "LEADER_ANNOUNCE"
