# protocol.py

# Message types
CLIENT_JOIN = "CLIENT_JOIN"
CREATE_CHATROOM = "CREATE_CHATROOM"
JOIN_CHATROOM = "JOIN_CHATROOM"
CHAT_MSG = "CHAT_MSG"
CHATROOMS_LIST = "CHATROOMS_LIST"
ROOM_ASSIGNMENT = "ROOM_ASSIGNMENT"
HEARTBEAT = "HEARTBEAT"

DISCOVER_SERVER = "DISCOVER_SERVER"
SERVER_ADVERTISEMENT = "SERVER_ADVERTISEMENT"

# Election
ELECTION = "ELECTION"
LEADER_ANNOUNCE = "LEADER_ANNOUNCE"
