# protocol.py

DISCOVER = "DISCOVER"
DISCOVER_REPLY = "DISCOVER_REPLY"

ELECTION = "ELECTION"
OK = "OK"
COORDINATOR = "COORDINATOR"

HEARTBEAT = "HEARTBEAT"

CLIENT_JOIN = "CLIENT_JOIN"
CHAT_ASSIGN = "CHAT_ASSIGN"
