# server/protocol.py

# Client ↔ Server
CLIENT_JOIN = "CLIENT_JOIN"
JOIN_ACK = "JOIN_ACK"

CHAT_MSG = "CHAT_MSG"
ACK = "ACK"
DELIVERED = "DELIVERED"
RESEND_REQUEST = "RESEND_REQUEST"

# Server ↔ Server
SERVER_UP = "SERVER_UP"
SERVER_INFO = "SERVER_INFO"

HEARTBEAT = "HEARTBEAT"

ELECTION = "ELECTION"
LEADER_ANNOUNCE = "LEADER_ANNOUNCE"
